apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: g-hosted-rollout
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/andrii-codefresh/canary-rollout.git
    targetRevision: HEAD
  destination:
    name: arn-aws-eks-us-east-1-882458141806-cluster-andrii
    namespace: g-hosted-rollout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
